### PR TITLE
Update text for Primary Platform selection

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates text for Choose Primary Platform.

#### Ticket Link
https://www.figma.com/file/BDolYCzc6CMCgVMa3U1p9B/MS-Teams-Sync---Choose-Primary-Platform?type=design&node-id=805-19549&mode=design&t=09nWqGQxgaGMpdRa-11

Screenshot 2024-03-12 at 8 55 58 AM

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
In view of the June release, I think this text is fine, but I note that the choice of enabling selective sync is presently optional. I'm wondering if we need a way of reflecting the current configuration in the text?

**Comment by johndavidlugtu** [comment]
@lieut-data ideally the copy on the select-platform page depends on whether the selective sync is enabled by the admin.

That said, from a June rollout perspective, as you mentioned, it should be fine -- we can assume it is enabled

**Comment by sbishel** [comment]
Update for Carrie's comments, added screenshot. Let me know if you want any other changes.

**Review by cwarnermm — APPROVED** [review]

**Review by johndavidlugtu — APPROVED** [review]
Thanks Scott

**Review by asaadmahmood — APPROVED** [review]

**Pull request merged**
