### PR TITLE
MM-56469 - change out library for converting html to markdown.

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Changes out the library used for converting HTML to Markdown. Also implements unit test for all the potential conversions we support...if any were missed, let's add them.

http://github.com/JohannesKaufmann/html-to-markdown

The prior library did not handle tables without a `THEAD` very well, tables create in MS Teams do not have this row. This library creates GibHub Flavored Markdown and is extensible via Plugins. 

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-56469

### CODE REVIEW

**Comment by sbishel** [comment]
@esarafianou - Not sure if security wants to review now or with the plugin as a whole later....

**Review by lieut-data — APPROVED** [review]
Wow, nice work @sbishel :)

**Review by hmhealey — APPROVED** [review]

**Review by esarafianou — APPROVED** [review]
LGTM. 


cc. @jupenur let me know if you'd like to have an extra look at the new library.

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel 
QA-deferring to test as bug bash post merge

**Pull request merged**
