### PR TITLE
Improve Users sync

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Refactor syncUsers so it reads better and  fixes the issue where users being activated and deactivated constantly.

We now do not create synthetic users if they are not present in MM but disabled on MS Teams

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56942
https://mattermost.atlassian.net/browse/MM-56886

### CODE REVIEW

**Comment by JulienTant** [comment]
I was reviewing the PR and accidentally committed and pushed fixes for something else here 😓 reverted now, sorry for the noise!

**Review by JulienTant — APPROVED** [review]
Thanks for the improvements and the comments!

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
@enahum there is a conflict, but other than that looks good to me.

**Comment by enahum** [comment]
@jespino can you help look into why the tests are failing?

**Comment by JulienTant** [comment]
@enahum I reran the job and everything went green! :)

**Pull request merged**
