### PR TITLE
[MM-58308] Add number of attachments

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Add a footer to the notification letting the user know if file attachments were sent:

image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58308

### CODE REVIEW

**Comment by lieut-data** [comment]
This looks great, @JulienTant! Could I trouble you to rebase on the (literally just pushed) https://github.com/mattermost/mattermost-plugin-msteams/pull/666 and add unit test coverage for these cases using the new framework? Apologies for moving the code slightly, but happy to help resolve any conflicts :p

**Comment by lieut-data** [comment]
(Updated link above to https://github.com/mattermost/mattermost-plugin-msteams/pull/667)

**Comment by JulienTant** [comment]
I was just adding tests :P Will rebase.

**Comment by JulienTant** [comment]
Rebased, still need to add tests

**Review by sbishel — APPROVED** [review]

**Comment by JulienTant** [comment]
@lieut-data added tests using the permutator :P Please do not refactor your test on the main branch 🤣

**Review by lieut-data — APPROVED** [review]
Sweet :D

**Comment by JulienTant** [comment]
@lieut-data updated this to exclude codeblocks and reply blocks from attachment count.

**Pull request merged**
