### PR TITLE
MM-57507 Improve OAuth Flow

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Centralizes OAuth flow.
Allows landing page to be refreshable
Updates the origin bot message after successful connection

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-57507
  Fixes https://mattermost.atlassian.net/browse/MM-57493

### CODE REVIEW

**Comment by sbishel** [comment]
@calebroseland - I just saw these Jira tickets...I think this PR handles these as well.
https://mattermost.atlassian.net/browse/MM-56913
https://mattermost.atlassian.net/browse/MM-57405

**Review by enahum — APPROVED** [review]
lgtm

**Comment by sbishel** [comment]
@calebroseland @mgdelacroix this should be good to go. I moved part of Jesse's PR over to change welcome message and send bot message when Primary platform changes.

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
