### PR TITLE
(chore) Rename plugin's userID to botUsertID

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Naming is king. Finally changing the `userID` property to `botUsertID`!

Not the most important PR... or is it?

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Yes! I love this – – – very important 😀 

But minor nit: should this be `botUserID` for maximum clarity?

**Comment by JulienTant** [comment]
Funny that you mentioned it, I ran a `\d bots` after I sent the PR to make sure they don't have their own ID... they used `user_id` as their PK. And I was thinking maybe it should be `botUserID` 🤣 Will change for clarity's sake!

**Review by sbishel — APPROVED** [review]
Nice...

**Comment by lieut-data** [comment]
Oops, typo `p.botUsertID` vs `p.botUserID`?

**Comment by JulienTant** [comment]
Oh nooo 😓

**Pull request merged**
